### ISSUE TITLE
Track upstream PR Henrik made and back onto upstream once it's merged and released

### ISSUE THREAD

**Issue by solarce** [travis-ci/jupiter-brain#35]
## Details 

....

Upstream PR: https://github.com/vmware/govmomi/pull/634

## Actions to take once upstream is ready for usage again
- [x] `gvt delete github.com/vmware/govmomi && gvt fetch github.com/vmware/govmomi`

**Comment by henrikhodne** [comment]
Upstream PR merged, PR to use upstream again is here: https://github.com/travis-ci/jupiter-brain/pull/39
